# Generated by Django 2.1.4 on 2019-07-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_newproduct',
            fields=[
                ('VPID', models.AutoField(primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=50)),
                ('CATEGORIES', models.CharField(max_length=50)),
                ('CATEGORIETYPE', models.CharField(max_length=50)),
                ('SIZE', models.CharField(max_length=20)),
                ('QUANTITY', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=100)),
                ('IMAGE', models.ImageField(upload_to='my_images')),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DESCRIPTION', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('IDNO', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=150)),
                ('PASSWORD', models.CharField(max_length=150)),
                ('EMAIL', models.EmailField(max_length=150)),
                ('MOBILENO', models.CharField(max_length=10)),
                ('OTP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Addresses',
            fields=[
                ('VAID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('HOUSENUMBER', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=150)),
                ('CITY', models.CharField(max_length=50)),
                ('STATE', models.CharField(max_length=50)),
                ('PINCODE', models.CharField(max_length=10)),
                ('LANDMARK', models.CharField(max_length=150)),
                ('PHONE', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_details',
            fields=[
                ('IDNO', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=150)),
                ('PASSWORD', models.CharField(max_length=150)),
                ('EMAIL', models.EmailField(max_length=150)),
                ('MOBILENO', models.CharField(max_length=10)),
                ('OTP', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vendor_addresses',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appe.Vendor_details'),
        ),
        migrations.AddField(
            model_name='add_newproduct',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appe.Vendor_details'),
        ),
    ]
