# Generated by Django 2.1.4 on 2019-07-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Addcart',
            fields=[
                ('CAID', models.AutoField(primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=50)),
                ('CATEGORIES', models.CharField(max_length=50)),
                ('CATEGORIETYPE', models.CharField(max_length=50)),
                ('SIZE', models.CharField(max_length=20)),
                ('QUANTITY', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=100)),
                ('IMAGE', models.ImageField(upload_to='my_images')),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appe.Customer_details')),
            ],
        ),
        migrations.RenameField(
            model_name='add_newproduct',
            old_name='name',
            new_name='V_P_ID',
        ),
        migrations.RenameField(
            model_name='vendor_addresses',
            old_name='name',
            new_name='V_A_ID',
        ),
    ]
